let articles = [
    {
        id : 1,
        title : "Creatine Supplements 101: Benefits, Side Effects And More",
        shortTitle : "Creatine closely follows whey protein in the list of most popular sports nutrition products. It’s convenient, it’s backed up byresearch and it’s a valuable part of nutrition .",
        dateandtime : "Oct 2 22 min read·",
        admin : "Doug Shapiro",
        link: "https://www.healthline.com/nutrition/creatine-safety-and-side-effects#side-effects" ,
        adminImg : "https://th.bing.com/th/id/R.eee50c879159f0b3b79c8725383d77dd?rik=xH9sJrSf5aJrlg&pid=ImgRaw&r=0" ,
        mainImg : "https://d.ibtimes.co.uk/en/full/1546282/creatine.jpg" ,
        image1 : "https://d.ibtimes.co.uk/en/full/1546282/creatine.jpg",
        image2 : "https://i.pinimg.com/originals/e5/0c/a1/e50ca1a5953ec03d7bf1d548fa9ef7b8.png",
        image3 : " https://avgjoefitness.com/wp-content/uploads/2019/01/creatinepic-e1548610790583.jpg",
        articleChunk1 : "Creatine is found throughout your body, with 95% of it stored in your muscles (2Trusted Source). It is obtained from meat and fish and can also be produced naturally in your body from amino acids (2Trusted Source).Your diet and natural creatine levels do not typically maximize muscle stores of this compound. The average stores are about 120 mmol/kg in someone who weighs 154 pounds (70 kg), but creatine supplements can elevate these stores to around 160 mmol/kg (2Trusted Source). During high intensity exercise, the stored creatine helps your muscles produce more energy. This is the main reason that creatine enhances exercise performance (2Trusted Source). Once you fill your muscle’s creatine stores, any extra is broken down into creatinine, which is metabolized by your liver and released in your urine (2Trusted Source).",
        articleChunk2 : "As with many supplements or medications, excessive doses may cause digestive issues. In a 2008 study, a 5-gram dose (taken twice per day) caused diarrhea in 29% of participants, which was not significantly different than the placebo. However, a 10-gram dose (taken once per day) increased diarrhea risk by 56% (21Trusted Source).For this reason, the recommended serving is set at 3–5 grams. The 20-gram loading protocol is also split into 4 servings of 5 grams each over a day (2Trusted Source).Despite anecdotal reports, there is no evidence that creatine causes digestive concerns when taken at recommended doses (22Trusted Source).It is possible that additives, ingredients, or contaminants generated during the industrial production of creatine can lead to issues (23Trusted Source).It is recommended that you purchase a trusted, high quality product.",
        articleChunk3 : "The bottom line : Creatine has been used for more than a century, and hundreds of studies support its safety and effectiveness.It also provides many benefits for muscle and performance, may improve markers of health, and is being used in medical settings to help treat various diseases.Creatine is one of the cheapest, most effective, and safest supplements available."
    },
    {
        id : 2,
        title : "Why You Need a Full-Body Workout Routine (and How to Get It)",
        shortTitle : "Why it Was Inevitable and What Happens Next",
        dateandtime : "Oct 2 22 min read·",
        admin : "Doug Shapiro",
        link: "https://www.omnilit.com/tl/sport/need-full-body-workout-routine-get/" ,
        mainImg : "https://www.omnilit.com/wp-content/uploads/2018/05/rwverveqrvceqr.jpg" ,
        image1 : "https://d.ibtimes.co.uk/en/full/1546282/creatine.jpg",
        image2 : "https://i.pinimg.com/originals/e5/0c/a1/e50ca1a5953ec03d7bf1d548fa9ef7b8.png",
        image3 : " https://avgjoefitness.com/wp-content/uploads/2019/01/creatinepic-e1548610790583.jpg",
        articleChunk1 : "BUSINESS INTERNET HEALTH T&L WORLD Why You Need a Full-Body Workout Routine (and How to Get It) May 22, 2018 2:31 amViews: 279 How much of your body is involved in your typical workout routine? If you’re like most average gym-goers, you have one or two exercises you favor, with minimal attention paid to other areas of your body. For example, you might be an avid runner, sticking to the treadmill but never venturing beyond the cardio area. Or you might work heavily on your upper body strength, but neglect your legs (resulting in “chicken legs” syndrome). It’s important to give your entire body a workout, one way or another. And even if you’re picky about which exercises you like to do, there are so many options, you’ll have no excuse. ",
        articleChunk2 : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas voluptate amet beatae voluptatibus odit similique unde dicta porro eius, ea accusantium dignissimos sapiente id provident deleniti expedita explicabo quaerat exercitationem. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, architecto voluptas consequuntur corporis est deleniti. Maiores magnam molestias accusamus aliquid inventore error officiis tenetur facilis blanditiis molestiae voluptatibus, quaerat nemo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet hic iure ratione dolor vitae at culpa asperiores ullam, suscipit cupiditate harum corrupti fugit explicabo aliquam, quos deleniti dicta officia? Aliquid. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ipsa corporis molestiae ipsum dolorum perferendis adipisci neque sed optio temporibus sit vel, dicta numquam, quibusdam cupiditate? Culpa ea nihil inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos aperiam atque praesentium. Dolor molestias facilis dolores, animi quas temporibus maxime. Culpa nulla hic amet maiores sunt qui impedit quis laudantium. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora commodi minima ipsum, odit beatae consequatur pariatur aliquid laborum placeat possimus quo iste tempore eaque dolor quae impedit ad nesciunt odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nulla doloremque assumenda fuga laborum unde asperiores et illum voluptatum libero necessitatibus aspernatur pariatur, ipsum atque vel ab doloribus sequi deleniti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium quos vero saepe fuga facere fugiat laboriosam fugit neque voluptatum dolorum porro deserunt aperiam rem eius, reiciendis dolor! Voluptatem, molestiae magni. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam vel tempore ea quis delectus sed ipsum libero voluptatum cum ducimus repudiandae maxime sunt, deleniti nisi corporis ipsa harum cumque saepe?",
        articleChunk3 : " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas voluptate amet beatae voluptatibus odit similique unde dicta porro eius, ea accusantium dignissimos sapiente id provident deleniti expedita explicabo quaerat exercitationem. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, architecto voluptas consequuntur corporis est deleniti. Maiores magnam molestias accusamus aliquid inventore error officiis tenetur facilis blanditiis molestiae voluptatibus, quaerat nemo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet hic iure ratione dolor vitae at culpa asperiores ullam, suscipit cupiditate harum corrupti fugit explicabo aliquam, quos deleniti dicta officia? Aliquid. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ipsa corporis molestiae ipsum dolorum perferendis adipisci neque sed optio temporibus sit vel, dicta numquam, quibusdam cupiditate? Culpa ea nihil inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos aperiam atque praesentium. Dolor molestias facilis dolores, animi quas temporibus maxime. Culpa nulla hic amet maiores sunt qui impedit quis laudantium. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora commodi minima ipsum, odit beatae consequatur pariatur aliquid laborum placeat possimus quo iste tempore eaque dolor quae impedit ad nesciunt odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nulla doloremque assumenda fuga laborum unde asperiores et illum voluptatum libero necessitatibus aspernatur pariatur, ipsum atque vel ab doloribus sequi deleniti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium quos vero saepe fuga facere fugiat laboriosam fugit neque voluptatum dolorum porro deserunt aperiam rem eius, reiciendis dolor! Voluptatem, molestiae magni. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam vel tempore ea quis delectus sed ipsum libero voluptatum cum ducimus repudiandae maxime sunt, deleniti nisi corporis ipsa harum cumque saepe?"
    },
    {
        id : 3,
        title : "Yoga as a potential therapy for cardiovascular disease",
        shortTitle : "It’s important to give your entire body a workout, one way or another. And even if you’re picky about which exercises you like to do, there are so many options, you’ll have no excuse.",
        dateandtime : "Oct 2 22 min read·",
        admin : "Doug Shapiro",
        link: "https://www.kurzweilai.net/yoga-as-a-potential-therapy-for-cardiovascular-disease-and-metabolic-syndrome" ,
        mainImg : "https://th.bing.com/th/id/R.6934fa57593dea743316c3df9efdcf78?rik=Devuy0w3pqkqpA&pid=ImgRaw&r=0" ,
        image1 : "https://d.ibtimes.co.uk/en/full/1546282/creatine.jpg",
        image2 : "https://i.pinimg.com/originals/e5/0c/a1/e50ca1a5953ec03d7bf1d548fa9ef7b8.png",
        image3 : " https://avgjoefitness.com/wp-content/uploads/2019/01/creatinepic-e1548610790583.jpg",
        articleChunk1 : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas voluptate amet beatae voluptatibus odit similique unde dicta porro eius, ea accusantium dignissimos sapiente id provident deleniti expedita explicabo quaerat exercitationem. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, architecto voluptas consequuntur corporis est deleniti. Maiores magnam molestias accusamus aliquid inventore error officiis tenetur facilis blanditiis molestiae voluptatibus, quaerat nemo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet hic iure ratione dolor vitae at culpa asperiores ullam, suscipit cupiditate harum corrupti fugit explicabo aliquam, quos deleniti dicta officia? Aliquid. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ipsa corporis molestiae ipsum dolorum perferendis adipisci neque sed optio temporibus sit vel, dicta numquam, quibusdam cupiditate? Culpa ea nihil inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos aperiam atque praesentium. Dolor molestias facilis dolores, animi quas temporibus maxime. Culpa nulla hic amet maiores sunt qui impedit quis laudantium. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora commodi minima ipsum, odit beatae consequatur pariatur aliquid laborum placeat possimus quo iste tempore eaque dolor quae impedit ad nesciunt odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nulla doloremque assumenda fuga laborum unde asperiores et illum voluptatum libero necessitatibus aspernatur pariatur, ipsum atque vel ab doloribus sequi deleniti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium quos vero saepe fuga facere fugiat laboriosam fugit neque voluptatum dolorum porro deserunt aperiam rem eius, reiciendis dolor! Voluptatem, molestiae magni. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam vel tempore ea quis delectus sed ipsum libero voluptatum cum ducimus repudiandae maxime sunt, deleniti nisi corporis ipsa harum cumque saepe?",
        articleChunk2 : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas voluptate amet beatae voluptatibus odit similique unde dicta porro eius, ea accusantium dignissimos sapiente id provident deleniti expedita explicabo quaerat exercitationem. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, architecto voluptas consequuntur corporis est deleniti. Maiores magnam molestias accusamus aliquid inventore error officiis tenetur facilis blanditiis molestiae voluptatibus, quaerat nemo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet hic iure ratione dolor vitae at culpa asperiores ullam, suscipit cupiditate harum corrupti fugit explicabo aliquam, quos deleniti dicta officia? Aliquid. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ipsa corporis molestiae ipsum dolorum perferendis adipisci neque sed optio temporibus sit vel, dicta numquam, quibusdam cupiditate? Culpa ea nihil inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos aperiam atque praesentium. Dolor molestias facilis dolores, animi quas temporibus maxime. Culpa nulla hic amet maiores sunt qui impedit quis laudantium. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora commodi minima ipsum, odit beatae consequatur pariatur aliquid laborum placeat possimus quo iste tempore eaque dolor quae impedit ad nesciunt odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nulla doloremque assumenda fuga laborum unde asperiores et illum voluptatum libero necessitatibus aspernatur pariatur, ipsum atque vel ab doloribus sequi deleniti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium quos vero saepe fuga facere fugiat laboriosam fugit neque voluptatum dolorum porro deserunt aperiam rem eius, reiciendis dolor! Voluptatem, molestiae magni. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam vel tempore ea quis delectus sed ipsum libero voluptatum cum ducimus repudiandae maxime sunt, deleniti nisi corporis ipsa harum cumque saepe?",
        articleChunk3 : " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas voluptate amet beatae voluptatibus odit similique unde dicta porro eius, ea accusantium dignissimos sapiente id provident deleniti expedita explicabo quaerat exercitationem. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, architecto voluptas consequuntur corporis est deleniti. Maiores magnam molestias accusamus aliquid inventore error officiis tenetur facilis blanditiis molestiae voluptatibus, quaerat nemo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet hic iure ratione dolor vitae at culpa asperiores ullam, suscipit cupiditate harum corrupti fugit explicabo aliquam, quos deleniti dicta officia? Aliquid. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ipsa corporis molestiae ipsum dolorum perferendis adipisci neque sed optio temporibus sit vel, dicta numquam, quibusdam cupiditate? Culpa ea nihil inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos aperiam atque praesentium. Dolor molestias facilis dolores, animi quas temporibus maxime. Culpa nulla hic amet maiores sunt qui impedit quis laudantium. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora commodi minima ipsum, odit beatae consequatur pariatur aliquid laborum placeat possimus quo iste tempore eaque dolor quae impedit ad nesciunt odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nulla doloremque assumenda fuga laborum unde asperiores et illum voluptatum libero necessitatibus aspernatur pariatur, ipsum atque vel ab doloribus sequi deleniti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium quos vero saepe fuga facere fugiat laboriosam fugit neque voluptatum dolorum porro deserunt aperiam rem eius, reiciendis dolor! Voluptatem, molestiae magni. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam vel tempore ea quis delectus sed ipsum libero voluptatum cum ducimus repudiandae maxime sunt, deleniti nisi corporis ipsa harum cumque saepe?"
    }
];

export function getArticles() {
    return articles;
}

export function getArticlesId(id) {
    return articles.find(
        (articles) => articles.id === id
    )
}

